services:

  vertx:
    container_name: vertx-oauth2
    image: vertx-oauth2-oidc:dev
    #restart: unless-stopped
    # map an outer port to the inner port 8081 our application is listening on
    ports:
      # - 8080:8081
      - 8080:8080
    environment:
      - GITHUB_CLIENT_ID=Ov23liSdnEklYKoHeDL8
      - GITHUB_CLIENT_SECRET=changeme
