services:

  vertx:
    container_name: vertx-oauth2
    image: vertx-oauth2-oidc:dev
    #restart: unless-stopped
    # map an outer port to the inner port 8081 our application is listening on
    ports:
      # - 8080:8081
      - 8080:8080
    environment:
      # - GITHUB_CLIENT_ID=Ov23liSdnEklYKoHeDL8
      # - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - KEYCLOAK_BASE_URL=https://172.17.0.1
      - KEYCLOAK_REALM=vertx
      - KEYCLOAK_CLIENT_ID=vertx-service
      - KEYCLOAK_CLIENT_SECRET=ecb85cc5-f90d-4a03-8fac-24dcde57f40c
